### ISSUE TITLE
Error when launching the script

### ISSUE THREAD

**Issue by Loubaris** [b3rt1ng/NOVA#1]
Traceback (most recent call last):
  File "main.py", line 298, in <module>
    main()
  File "main.py", line 163, in main
    hosts = infoga()
  File "main.py", line 135, in infoga
    ip = scanner()
  File "main.py", line 71, in scanner
    ip_inscan = ip_cropped+str(i)
UnboundLocalError: local variable 'ip_cropped' referenced before assignment

**Comment by b3rt1ng** [comment]
This is due to the method I use to detect the user IP, for the moment the program assumes that you are using "wlan0" but I'm working on a way to detect the interface you use to deal with your network.

Otherwise, you can directly type in your address by typing "-ip *your local ip*" and it'll assume that what you typed is your local address anyway.
